# Generated by Django 6.0.4 on 2026-04-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ananta", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiry",
            old_name="budget_range",
            new_name="budget",
        ),
        migrations.RenameField(
            model_name="enquiry",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="enquiry",
            old_name="service_required",
            new_name="service",
        ),
        migrations.AlterModelTable(
            name="enquiry",
            table="ananta_enquiry",
        ),
    ]
