# Generated by Django 6.0.4 on 2026-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananta", "0002_rename_budget_range_enquiry_budget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen"),
                            ("doors", "Doors"),
                            ("furniture", "Furniture"),
                            ("decor", "Decor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="products/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Pro",
            },
        ),
    ]
