# Generated by Django 6.0.4 on 2026-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananta", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=100),
        ),
    ]
