# Generated by Django 6.0.4 on 2026-04-21 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananta", "0004_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ananta_gallery_project",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AlterModelTable(
            name="product",
            table="ananta_products",
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ananta.galleryproject",
                    ),
                ),
            ],
            options={
                "db_table": "ananta_gallery_images",
            },
        ),
    ]
