# Generated by Django 6.0.4 on 2026-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ananta", "0005_galleryproject_alter_product_table_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
